# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a48e8b83aea547377d00a5119e11aa93a1ae40a52524540e18f80e965825561f005e2c87b613e146115e156e4268aead3253f7d0841fcb2fe99ecc733783d5bf

test:
  secret_key_base: 677f90897a617c21d8e2238b30981af0aee3c8300cd88b946a5a00b2d3fb04a28daa18fcfd28be15304801502ffcca0c26db0ce73a924f455c1e9434e5f62e14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
